In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from matplotlib.pylab import rcParams
rcParams['figure.figsize'] = 15,8

- 반도체 제조 공장에서 센서로부터 수집된 신호와 변수들을 모니터링한 데이터

In [2]:
Data = pd.read_csv('uci-secom.csv',  encoding='UTF-8',  engine='python')
Data.head()

Time        0        1          2          3       4      5  \
0  2008-07-19 11:55  3030.93  2564.00  2187.7333  1411.1265  1.3602  100.0   
1  2008-07-19 12:32  3095.78  2465.14  2230.4222  1463.6606  0.8294  100.0   
2  2008-07-19 13:17  2932.61  2559.94  2186.4111  1698.0172  1.5102  100.0   
3  2008-07-19 14:43  2988.72  2479.90  2199.0333   909.7926  1.3204  100.0   
4  2008-07-19 15:22  3032.24  2502.87  2233.3667  1326.5200  1.5334  100.0   

          6       7       8  ...       581     582     583     584      585  \
0   97.6133  0.1242  1.5005  ...       NaN  0.5005  0.0118  0.0035   2.3630   
1  102.3433  0.1247  1.4966  ...  208.2045  0.5019  0.0223  0.0055   4.4447   
2   95.4878  0.1241  1.4436  ...   82.8602  0.4958  0.0157  0.0039   3.1745   
3  104.2367  0.1217  1.4882  ...   73.8432  0.4990  0.0103  0.0025   2.0544   
4  100.3967  0.1235  1.5031  ...       NaN  0.4800  0.4766  0.1045  99.3032   

      586     587     588       589  Pass/Fail  
0     NaN     NaN     NaN       NaN         -1  
1  0.0096  0.0201  0.0060  208.2045         -1  
2  0.0584  0.0484  0.0148   82.8602          1  
3  0.0202  0.0149  0.0044   73.8432         -1  
4  0.0202  0.0149  0.0044   73.8432         -1  

[5 rows x 592 columns]

In [5]:
Data['Pass/Fail'].value_counts()

-1    1449
 1     118
Name: Pass/Fail, dtype: int64

In [7]:
Data=pd.DataFrame(data=Data)
Data = Data.drop('Time', axis=1)
Data.head()

0        1          2          3       4      5         6       7  \
0  3030.93  2564.00  2187.7333  1411.1265  1.3602  100.0   97.6133  0.1242   
1  3095.78  2465.14  2230.4222  1463.6606  0.8294  100.0  102.3433  0.1247   
2  2932.61  2559.94  2186.4111  1698.0172  1.5102  100.0   95.4878  0.1241   
3  2988.72  2479.90  2199.0333   909.7926  1.3204  100.0  104.2367  0.1217   
4  3032.24  2502.87  2233.3667  1326.5200  1.5334  100.0  100.3967  0.1235   

        8       9  ...       581     582     583     584      585     586  \
0  1.5005  0.0162  ...       NaN  0.5005  0.0118  0.0035   2.3630     NaN   
1  1.4966 -0.0005  ...  208.2045  0.5019  0.0223  0.0055   4.4447  0.0096   
2  1.4436  0.0041  ...   82.8602  0.4958  0.0157  0.0039   3.1745  0.0584   
3  1.4882 -0.0124  ...   73.8432  0.4990  0.0103  0.0025   2.0544  0.0202   
4  1.5031 -0.0031  ...       NaN  0.4800  0.4766  0.1045  99.3032  0.0202   

      587     588       589  Pass/Fail  
0     NaN     NaN       NaN         -1  
1  0.0201  0.0060  208.2045         -1  
2  0.0484  0.0148   82.8602          1  
3  0.0149  0.0044   73.8432         -1  
4  0.0149  0.0044   73.8432         -1  

[5 rows x 591 columns]

In [8]:
#컬럼명 변경
a = []

for i in range(0,590):
    columns_number = 'A%d'%(i)
    a.append(columns_number)

a.append('result')
a

Data.columns = a

Data.head()

A0       A1         A2         A3      A4     A5        A6      A7  \
0  3030.93  2564.00  2187.7333  1411.1265  1.3602  100.0   97.6133  0.1242   
1  3095.78  2465.14  2230.4222  1463.6606  0.8294  100.0  102.3433  0.1247   
2  2932.61  2559.94  2186.4111  1698.0172  1.5102  100.0   95.4878  0.1241   
3  2988.72  2479.90  2199.0333   909.7926  1.3204  100.0  104.2367  0.1217   
4  3032.24  2502.87  2233.3667  1326.5200  1.5334  100.0  100.3967  0.1235   

       A8      A9  ...      A581    A582    A583    A584     A585    A586  \
0  1.5005  0.0162  ...       NaN  0.5005  0.0118  0.0035   2.3630     NaN   
1  1.4966 -0.0005  ...  208.2045  0.5019  0.0223  0.0055   4.4447  0.0096   
2  1.4436  0.0041  ...   82.8602  0.4958  0.0157  0.0039   3.1745  0.0584   
3  1.4882 -0.0124  ...   73.8432  0.4990  0.0103  0.0025   2.0544  0.0202   
4  1.5031 -0.0031  ...       NaN  0.4800  0.4766  0.1045  99.3032  0.0202   

     A587    A588      A589  result  
0     NaN     NaN       NaN      -1  
1  0.0201  0.0060  208.2045      -1  
2  0.0484  0.0148   82.8602       1  
3  0.0149  0.0044   73.8432      -1  
4  0.0149  0.0044   73.8432      -1  

[5 rows x 591 columns]

In [9]:
Data.dtypes

A0        float64
A1        float64
A2        float64
A3        float64
A4        float64
           ...   
A586      float64
A587      float64
A588      float64
A589      float64
result      int64
Length: 591, dtype: object

In [10]:
Data.isnull().sum(axis=1)

0        44
1        36
2        20
3        20
4        40
       ... 
1562     52
1563     52
1564    148
1565     60
1566    152
Length: 1567, dtype: int64

In [11]:
#NAN 50개 이상 행 삭제
Data = Data.dropna(axis = 0, thresh = len(Data.columns) - 50)
Data.isnull().sum(1)

0       44
1       36
2       20
3       20
4       40
        ..
1545    48
1546    48
1550    16
1557    48
1559    48
Length: 1517, dtype: int64

In [12]:
Data = Data.fillna(Data.mean())

In [13]:
Data

A0       A1         A2         A3      A4     A5        A6      A7  \
0     3030.93  2564.00  2187.7333  1411.1265  1.3602  100.0   97.6133  0.1242   
1     3095.78  2465.14  2230.4222  1463.6606  0.8294  100.0  102.3433  0.1247   
2     2932.61  2559.94  2186.4111  1698.0172  1.5102  100.0   95.4878  0.1241   
3     2988.72  2479.90  2199.0333   909.7926  1.3204  100.0  104.2367  0.1217   
4     3032.24  2502.87  2233.3667  1326.5200  1.5334  100.0  100.3967  0.1235   
...       ...      ...        ...        ...     ...    ...       ...     ...   
1545  3100.19  2490.60  2212.8445  1068.5644  1.7835  100.0  113.8833  0.1249   
1546  3093.24  2488.18  2212.8445  1068.5644  1.7835  100.0  113.8833  0.1249   
1550  3072.20  2406.47  2195.4444  2914.1792  1.5978  100.0   85.1011  0.1235   
1557  3072.10  2534.87  2177.4333  2945.8855  1.3321  100.0   83.1700  0.1253   
1559  3076.33  2456.13  2217.4111  1032.2836  1.4802  100.0  101.3511  0.1195   

          A8      A9  ...        A581    A582    A583    A584     A585  \
0     1.5005  0.0162  ...   96.868958  0.5005  0.0118  0.0035   2.3630   
1     1.4966 -0.0005  ...  208.204500  0.5019  0.0223  0.0055   4.4447   
2     1.4436  0.0041  ...   82.860200  0.4958  0.0157  0.0039   3.1745   
3     1.4882 -0.0124  ...   73.843200  0.4990  0.0103  0.0025   2.0544   
4     1.5031 -0.0031  ...   96.868958  0.4800  0.4766  0.1045  99.3032   
...      ...     ...  ...         ...     ...     ...     ...      ...   
1545  1.4294 -0.0014  ...  402.687400  0.4951  0.0165  0.0051   3.3383   
1546  1.3482  0.0060  ...  105.714200  0.5022  0.0249  0.0049   4.9623   
1550  1.3148 -0.0024  ...   27.551400  0.5034  0.0178  0.0043   3.5459   
1557  1.4359 -0.0114  ...   26.733000  0.5010  0.0132  0.0035   2.6249   
1559  1.3120 -0.0043  ...  117.456400  0.4960  0.0157  0.0036   3.1743   

          A586      A587      A588        A589  result  
0     0.021535  0.016475  0.005284   99.024497      -1  
1     0.009600  0.020100  0.006000  208.204500      -1  
2     0.058400  0.048400  0.014800   82.860200       1  
3     0.020200  0.014900  0.004400   73.843200      -1  
4     0.020200  0.014900  0.004400   73.843200      -1  
...        ...       ...       ...         ...     ...  
1545  0.006300  0.025200  0.007000  402.687400      -1  
1546  0.013400  0.014200  0.004700  105.714200      -1  
1550  0.023600  0.006500  0.002200   27.551400      -1  
1557  0.027700  0.007400  0.002300   26.733000      -1  
1559  0.015000  0.017600  0.005700  117.456400      -1  

[1517 rows x 591 columns]

In [14]:
a = Data.corrwith(Data.result)
k = a.sort_values(axis=0, ascending=True)

In [15]:
k

A28    -0.124181
A26    -0.116572
A316   -0.107560
A125   -0.106308
A122   -0.096303
          ...   
A534         NaN
A535         NaN
A536         NaN
A537         NaN
A538         NaN
Length: 591, dtype: float64

In [16]:
k

A28    -0.124181
A26    -0.116572
A316   -0.107560
A125   -0.106308
A122   -0.096303
          ...   
A534         NaN
A535         NaN
A536         NaN
A537         NaN
A538         NaN
Length: 591, dtype: float64

In [17]:
k = k.dropna()
k.index

Index(['A28', 'A26', 'A316', 'A125', 'A122', 'A127', 'A180', 'A452', 'A22',
       'A14',
       ...
       'A348', 'A510', 'A436', 'A435', 'A430', 'A434', 'A431', 'A103', 'A59',
       'result'],
      dtype='object', length=475)

In [18]:
k = k.dropna()
b = k.index
# for i in k:
#     k = k.replace(i,abs(i))
k.sort_values(axis=0, ascending=False)

result    1.000000
A59       0.190140
A103      0.170896
A431      0.155228
A434      0.149857
            ...   
A122     -0.096303
A125     -0.106308
A316     -0.107560
A26      -0.116572
A28      -0.124181
Length: 475, dtype: float64

In [19]:
len(k)

475

In [20]:
k.index[1]

'A26'

In [21]:
useful_columns = [] 
for i in range(len(k)):
    if k[i] >= 0.1:
        useful_columns.append(k.index[i])
    elif k[i] <= -0.1:
        useful_columns.append(k.index[i])
useful_columns

['A28',
 'A26',
 'A316',
 'A125',
 'A79',
 'A159',
 'A160',
 'A295',
 'A129',
 'A294',
 'A210',
 'A165',
 'A300',
 'A164',
 'A299',
 'A21',
 'A163',
 'A298',
 'A348',
 'A510',
 'A436',
 'A435',
 'A430',
 'A434',
 'A431',
 'A103',
 'A59',
 'result']

In [22]:
features = useful_columns

In [23]:
X = Data[features]
X

A28     A26    A316    A125       A79    A159   A160      A295  \
0     64.2333  1.7730  6.2698  0.8656 -0.008300  1017.0  967.0  398.3185   
1     68.4222  2.0143  5.6522  0.8703 -0.035800   568.0   59.0   26.5879   
2     67.1333  2.0295  5.7247  0.8798 -0.005400   562.0  788.0  329.6406   
3     62.9333  2.0038  5.4440  1.3660  0.067600   859.0  355.0  157.0889   
4     62.8333  1.9912  4.8956  0.9460  0.003400   699.0  283.0  128.0296   
...       ...     ...     ...     ...       ...     ...    ...       ...   
1545  72.8556  1.9910  6.1135  1.5410  0.003588   844.0  462.0  209.1513   
1546  71.0444  1.9840  7.3467  1.5410  0.003588  1254.0  760.0  316.1786   
1550  72.3333  1.9987  7.3852  1.3900  0.009300   545.0  739.0  304.6714   
1557  71.4222  2.0252  5.5391  1.3090  0.003588  1513.0  870.0  359.9559   
1559  73.0222  1.9960  8.7513  1.3430  0.003588  1305.0  364.0  169.4016   

        A129      A294  ...      A348      A510    A436    A435     A430  \
0    -0.0473  418.1363  ...  0.021500   64.6707  3.1158  2.7073  18.7673   
1    -0.0946  233.9865  ...  0.014200  141.4365  1.6779  5.7093  10.4383   
2    -0.1892  251.4536  ...  0.010500  240.7767  0.8972  5.7650  10.3162   
3     0.2838  415.5048  ...  0.040700  113.5593  1.3671  5.3899  15.7089   
4    -0.5677  319.1252  ...  0.024600  148.0663  1.5533  2.0088  12.7642   
...      ...       ...  ...       ...       ...     ...     ...      ...   
1545  0.0000  375.3979  ...  0.024743   44.0831  4.5425  4.1688  15.8089   
1546  0.0000  599.6418  ...  0.024743   37.6840  3.2056  4.9899  24.8010   
1550 -0.5677  265.1276  ...  0.027200   42.1053  1.9812  3.1019   9.5163   
1557 -0.1419  646.8108  ...  0.024743   55.4855  3.5422  7.7028  25.1298   
1559 -0.8515  555.3476  ...  0.024743   88.6747  3.5463  2.4549  24.0431   

         A434     A431    A103      A59  result  
0     10.0503  33.1562 -0.0042  -1.7264      -1  
1      8.6336   2.2655 -0.0045   0.8073      -1  
2     14.2503  29.1663 -0.0026  23.8245       1  
3      5.1760  13.4051 -0.0059  24.3791      -1  
4     11.4064  10.7390 -0.0045 -12.2945      -1  
...       ...      ...     ...      ...     ...  
1545  13.4992  16.9744 -0.0138   4.6964      -1  
1546  13.1569  29.6267 -0.0127  -2.4436      -1  
1550  14.4074  27.4517 -0.0090   3.0682      -1  
1557  15.8597  32.3691 -0.0099   0.0627      -1  
1559   5.4525  13.9879 -0.0104  -3.1909      -1  

[1517 rows x 28 columns]

In [24]:
# for i in Data.columns:
#     if str(i) not in useful_columns:
#         del Data[str(i)] 

# Data

In [25]:
X.corrwith(X.result)

A28      -0.124181
A26      -0.116572
A316     -0.107560
A125     -0.106308
A79       0.106934
A159      0.107025
A160      0.108389
A295      0.112648
A129      0.112788
A294      0.113615
A210      0.113751
A165      0.114154
A300      0.115133
A164      0.119870
A299      0.120212
A21       0.125842
A163      0.127241
A298      0.131371
A348      0.138274
A510      0.142318
A436      0.145447
A435      0.147084
A430      0.148304
A434      0.149857
A431      0.155228
A103      0.170896
A59       0.190140
result    1.000000
dtype: float64

In [26]:
Data.corrwith(Data.result)

A0       -0.035190
A1       -0.003759
A2        0.006352
A3       -0.021353
A4       -0.014768
            ...   
A586      0.015289
A587      0.038052
A588      0.032818
A589     -0.008386
result    1.000000
Length: 591, dtype: float64

In [27]:
sns.heatmap(Data.corr(), annot=True, cmap="coolwarm")

KeyboardInterrupt: 

Error in callback <function flush_figures at 0x7fd8447033b0> (for post_execute):


KeyboardInterrupt: 

### 데이터 셋


In [28]:
from sklearn import datasets
from sklearn.model_selection import cross_val_score

In [29]:
Data.columns

Index(['A0', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9',
       ...
       'A581', 'A582', 'A583', 'A584', 'A585', 'A586', 'A587', 'A588', 'A589',
       'result'],
      dtype='object', length=591)

In [48]:
features = Data.columns.difference(['result'])

In [102]:
features = ['A153','A166','A196', 'A2', 'A239', 'A252', 'A26', 'A285', 'A304', 'A318',
           'A333','A344', 'A348', 'A359', 'A40', 'A409', 'A455', 'A475', 'A520', 
           'A523','A59', 'A65','A99'  ]

In [103]:
X = Data[features]
y = Data.result

In [104]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle=True, test_size=0.3)

In [105]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1061, 23)
(456, 23)
(1061,)
(456,)


### Decsion Tree

In [106]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree

In [107]:
DT_model = DecisionTreeClassifier(max_depth=7)

In [108]:
#Cross validataion
scores = cross_val_score(DT_model, X_train, y_train, cv=4)
print("Corss validation scores :{}".format(scores))
print("Corss validation means :{:.3f}".format(scores.mean()))

Corss validation scores :[0.92105263 0.92830189 0.91320755 0.90188679]
Corss validation means :0.916


In [109]:
DT_model.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=7, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [110]:
prediction_dt = DT_model.predict(X_test)
prediction_dt

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1,  1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1,  1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1

In [111]:
list(zip(X.columns, DT_model.feature_importances_))

[('A153', 0.16953330561762922),
 ('A166', 0.026295235578468273),
 ('A196', 0.024553411266977507),
 ('A2', 0.10745663644470448),
 ('A239', 0.0),
 ('A252', 0.018851936814893812),
 ('A26', 0.10267054819188302),
 ('A285', 0.0),
 ('A304', 0.07184452403741955),
 ('A318', 0.0),
 ('A333', 0.021253504302438487),
 ('A344', 0.0),
 ('A348', 0.09393020048197351),
 ('A359', 0.0),
 ('A40', 0.0),
 ('A409', 0.03175063042508432),
 ('A455', 0.04634434466994729),
 ('A475', 0.0564963492931375),
 ('A520', 0.07362354609673712),
 ('A523', 0.0),
 ('A59', 0.12222054796818065),
 ('A65', 0.0),
 ('A99', 0.0331752788105251)]

In [112]:
X_train.columns

Index(['A153', 'A166', 'A196', 'A2', 'A239', 'A252', 'A26', 'A285', 'A304',
       'A318', 'A333', 'A344', 'A348', 'A359', 'A40', 'A409', 'A455', 'A475',
       'A520', 'A523', 'A59', 'A65', 'A99'],
      dtype='object')

In [113]:
from sklearn import metrics
metrics.accuracy_score(y_test, prediction_dt)

0.9166666666666666

In [114]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score


def get_clf_eval(y_test, y_pred):
    confusion = confusion_matrix(y_test, y_pred)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    F1 = f1_score(y_test, y_pred)
    print('Confusion Matrix\n', confusion)
    print('\nAccuracy: {:.4f}'.format(accuracy))
    print('Precision(정밀도): {:.4f}'.format(precision))
    print('Recall(재현율): {:.4f}'.format(recall))
    print('F1: {:.4f}'.format(F1))

In [115]:
get_clf_eval(y_test, prediction_dt)

Confusion Matrix
 [[414  12]
 [ 26   4]]

Accuracy: 0.9167
Precision(정밀도): 0.2500
Recall(재현율): 0.1333
F1: 0.1739


### RandomForest

In [126]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

RF_model = RandomForestClassifier(n_estimators = 1000, random_state=13, max_depth=7)

param_grid = {
    'max_depth': [3, 5, 6, 8],
    'min_samples_split': [0.01, 0.05, 0.1],
    'max_features': ['auto', 'sqrt'],
}



In [127]:
RF_model.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=7, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=13, verbose=0,
                       warm_start=False)

In [72]:
gridsearch_rf = GridSearchCV(estimator=RF_model, param_grid=param_grid, scoring='accuracy', cv=5, n_jobs=-1)
gridsearch_rf.fit(X_train, y_train)

GridSearchCV(cv=5, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=1000, n_jobs=None,
                                              oob_score=False, random_state=13,
                                 

In [73]:
print('best params', gridsearch_rf.best_params_)
print('best score', gridsearch_rf.best_score_) 

best params {'max_depth': 8, 'max_features': 'auto', 'min_samples_split': 0.01}
best score 0.9255425635574455


In [74]:
#Cross validataion
scores = cross_val_score(gridsearch_rf, X_train, y_train, cv=5)
print("Corss validation scores :{}".format(scores))
print("Corss validation means :{:.3f}".format(scores.mean()))

Corss validation scores :[0.92488263 0.9245283  0.9245283  0.9245283  0.9245283 ]
Corss validation means :0.925


In [128]:
prediction = RF_model.predict(X_test)
prediction

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1

In [75]:
prediction_rf = gridsearch_rf.predict(X_test)
prediction_rf

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1

In [129]:
metrics.accuracy_score(y_test, prediction)

0.9342105263157895

In [130]:
get_clf_eval(y_test, prediction_rf)

Confusion Matrix
 [[426   0]
 [ 30   0]]

Accuracy: 0.9342
Precision(정밀도): 0.0000
Recall(재현율): 0.0000
F1: 0.0000


### XGBoost

In [132]:
!pip install xgboost

In [133]:
from xgboost import XGBClassifier

XGBoostError: XGBoost Library (libxgboost.dylib) could not be loaded.
Likely causes:
  * OpenMP runtime is not installed (vcomp140.dll or libgomp-1.dll for Windows, libomp.dylib for Mac OSX, libgomp.so for Linux and other UNIX-like OSes). Mac OSX users: Run `brew install libomp` to install OpenMP runtime.
  * You are running 32-bit Python on a 64-bit OS
Error message(s): ['dlopen(/opt/anaconda3/lib/python3.7/site-packages/xgboost/lib/libxgboost.dylib, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib\n  Referenced from: /opt/anaconda3/lib/python3.7/site-packages/xgboost/lib/libxgboost.dylib\n  Reason: image not found']


In [46]:
xgboost = XGBClassifier(learning_rate = 0.1, random_state=13)

gridsearch_xg = GridSearchCV(estimator=xgboost, param_grid=param_grid, scoring='accuracy', cv=5, n_jobs=-1)
gridsearch_xg.fit(X_train, y_train)

[09:24:58] WARNING: C:\Users\Administrator\workspace\xgboost-win64_release_1.1.0\src\learner.cc:480: 
Parameters: { max_features, min_samples_split } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.




GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=XGBClassifier(base_score=None, booster=None,
                                     colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None, gamma=None,
                                     gpu_id=None, importance_type='gain',
                                     interaction_constraints=None,
                                     learning_rate=0.1, max_delta_step=None,
                                     max_depth=None, min_child_weight=None,
                                     missing=nan, monotone_constrain...
                                     reg_lambda=None, scale_pos_weight=None,
                                     subsample=None, tree_method=None,
                                     validate_parameters=None, verbosity=None),
             iid='warn', n_jobs=-1,
             param_grid={'max_depth': [3, 5, 6, 8],
     

In [47]:
print('best params', gridsearch_xg.best_params_)
print('best score', gridsearch_xg.best_score_) 

best params {'max_depth': 6, 'max_features': 'auto', 'min_samples_split': 0.01, 'n_estimators': 150}
best score 0.9245994344957588


In [48]:
#Cross validataion
scores = cross_val_score(gridsearch_xg, X_train, y_train, cv=5)
print("Corss validation scores :{}".format(scores))
print("Corss validation means :{:.3f}".format(scores.mean()))

[09:27:03] WARNING: C:\Users\Administrator\workspace\xgboost-win64_release_1.1.0\src\learner.cc:480: 
Parameters: { max_features, min_samples_split } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[09:28:37] WARNING: C:\Users\Administrator\workspace\xgboost-win64_release_1.1.0\src\learner.cc:480: 
Parameters: { max_features, min_samples_split } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[09:30:09] WARNING: C:\Users\Administrator\workspace\xgboost-win64_release_1.1.0\src\learner.cc:480: 
Parameters: { max_features, min_samples_split } might not be used.

  This may n

In [49]:
prediction_xg = gridsearch_xg.predict(X_test)
prediction_xg

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1, -1,  1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1

In [6]:
prediction_xg.value_counts()

NameError: name 'prediction_xg' is not defined

In [50]:
metrics.accuracy_score(y_test, prediction_xg)

0.9210526315789473

In [51]:
get_clf_eval(y_test, prediction_xg)

Confusion Matrix
 [[418   4]
 [ 32   2]]

Accuracy: 0.9211
Precision(정밀도): 0.3333
Recall(재현율): 0.0588
F1: 0.1000
